/* generated by tools/split.py - do not edit by hand */
"use strict";
var CACHE_PREFIX = "bec-";
var CACHE_VERSION = "b44b51578a7849d1";
var CACHE_NAME = CACHE_PREFIX + CACHE_VERSION;
var PRECACHE_URLS = [
  "./",
  "./index.html",
  "./css/styles.css",
  "./data/pages.json",
  "./fonts/atkinson-bold.woff2",
  "./fonts/atkinson-regular.woff2",
  "./icons/apple-touch-icon-180.png",
  "./icons/favicon.svg",
  "./icons/icon-192.png",
  "./icons/icon-512.png",
  "./icons/icon-maskable-512.png",
  "./img/06f498a3a285.webp",
  "./img/1001495565ea.webp",
  "./img/194d08656401.webp",
  "./img/21c7e124275b.webp",
  "./img/2612008c678b.webp",
  "./img/2ae1579a0cdc.webp",
  "./img/2c15a917c86a.webp",
  "./img/30335d53b67d.webp",
  "./img/326720d3128b.webp",
  "./img/34bd18340b19.webp",
  "./img/372922b3a19a.webp",
  "./img/43a76e0cb247.webp",
  "./img/47733c0b81cc.webp",
  "./img/4887a6be72aa.webp",
  "./img/55340ab86b21.webp",
  "./img/58f34c26be86.webp",
  "./img/784f8ba3e456.webp",
  "./img/79e71b165904.webp",
  "./img/7fc5e02d15e5.webp",
  "./img/817655ca30b3.webp",
  "./img/875aed96c9df.webp",
  "./img/892c08319e9d.webp",
  "./img/8cc817cc778e.webp",
  "./img/8cf9e56761b2.webp",
  "./img/8e6dc70e3859.webp",
  "./img/92d345e0d46b.webp",
  "./img/982ccabc09ed.webp",
  "./img/ab5f727b9b41.webp",
  "./img/b7b664009686.webp",
  "./img/bd8537720b08.webp",
  "./img/e9985a8d5ebc.webp",
  "./img/f16d85ad20db.webp",
  "./img/f95619c8efb8.webp",
  "./img/fccb62d58908.webp",
  "./img/fe829da38934.webp",
  "./js/app.js",
  "./manifest.webmanifest"
];

self.addEventListener("install", function(event) {
  event.waitUntil(
    caches.open(CACHE_NAME).then(function(cache) {
      return Promise.all(PRECACHE_URLS.map(function(url) {
        return cache.add(new Request(url, {cache: "reload"})).catch(function(err) {
          console.error("Service worker install failed to cache:", url, err);
          throw err;
        });
      }));
    })
  );
});

self.addEventListener("activate", function(event) {
  event.waitUntil(
    caches.keys().then(function(names) {
      return Promise.all(
        names.filter(function(n) { return n.indexOf(CACHE_PREFIX) === 0 && n !== CACHE_NAME; })
             .map(function(n) { return caches.delete(n); })
      );
    }).then(function() { return self.clients.claim(); })
  );
});

self.addEventListener("message", function(event) {
  if (event.data && event.data.type === "SKIP_WAITING") self.skipWaiting();
});

self.addEventListener("fetch", function(event) {
  if (event.request.method !== "GET") return;
  var url = new URL(event.request.url);
  if (url.origin !== self.location.origin) return;
  event.respondWith(
    caches.match(event.request).then(function(cached) {
      if (cached) return cached;
      return fetch(event.request).catch(function() {
        return caches.match("./index.html");
      });
    })
  );
});
